#!/usr/bin/env bash

if [ -e /usr/bin/SoftwareRender ]; then
    cp /usr/bin/SoftwareRender /usr/bin/SoftwareRender.bak
    mv /usr/bin/big-SoftwareRender /usr/bin/SoftwareRender
fi

if [ -e /usr/share/dbus-1/services/org.manjaro.pamac.manager.service ]; then
    cp /usr/share/dbus-1/services/org.manjaro.pamac.manager.service /usr/share/dbus-1/services/org.manjaro.pamac.manager.service.bak
    mv /usr/share/dbus-1/services/big-org.manjaro.pamac.manager.service /usr/share/dbus-1/services/org.manjaro.pamac.manager.service
fi
