#!/usr/bin/env bash

ddeSessionBig="/usr/bin/dde-session-big"
ddeSessionBin="/usr/bin/dde-session"
wrapperScript="/usr/bin/startdde-biglinux"

# Renomeia o binário original, se ainda não foi renomeado
if [ -f "$ddeSessionBin" ] && [ ! -f "$ddeSessionBig" ]; then
	mv -f "$ddeSessionBin" "$ddeSessionBig"
fi

# Copia o script wrapper para substituir o dde-session
cp -f "$wrapperScript" "$ddeSessionBin"
chmod +x "$ddeSessionBin"
