#!/bin/bash

ddeSessionBin="/usr/bin/dde-session"
ddeSessionOriginalBin="/usr/bin/dde-session-original"
wrapperScript="/usr/bin/startdde-biglinux"

# Renomeia o binário original, se ainda não foi renomeado
if [ -f "$ddeSessionBin" ] && [ ! -f "$ddeSessionOriginalBin" ]; then
    mv "$ddeSessionBin" "$ddeSessionOriginalBin"
fi

# Copia o script wrapper para substituir o dde-session
cp "$wrapperScript" "$ddeSessionBin"
chmod +x "$ddeSessionBin"
